src/Microsoft.Framework.OptionsModel/project.json
Relies on https://github.com/aspnet/DependencyInjection/pull/195
/cc @HaoK @davidfowl @Eilon
=> Depend on the DI Interfaces package instead of the implementation package

test/Microsoft.Framework.OptionsModel.Test/OptionsTest.cs
PR that will be merged once the configuration API changes are pushed.
=> React to configuration API changes

src/Microsoft.Framework.OptionsModel/OptionsServices.cs, test/Microsoft.Framework.OptionsModel.Test/OptionsTest.cs
=> Support binding Nullable<T> from IConfiguration:

build.cmd, build.sh, src/Microsoft.Framework.OptionsModel/OptionsServices.cs, src/Microsoft.Framework.OptionsModel/project.json, test/Microsoft.Framework.OptionsModel.Test/project.json
Prepping to be merged once ready.
=> Update aspnet50/aspnetcore50 => dnx50/dnxcore50.

src/Microsoft.Framework.OptionsModel/OptionsServices.cs
Had to tweak the reflection code to run on all targets
Fixes https://github.com/aspnet/Options/issues/35
cc @divega
=> Remove conditional compilation for options

test/Microsoft.Framework.OptionsModel.Test/ConfigurationCollectionBindingTests.cs
@Eilon these are tests that you asked to add [here](https://github.com/aspnet/Options/issues/60#issuecomment-98031781)
=> Tests for config collection binding with non string values

src/Microsoft.Framework.OptionsModel/ConfigurationBinder.cs
=> Fix build break due to Configuration rename

src/Microsoft.Framework.OptionsModel/project.json
Depends on aspnet/DependencyInjection#245
=> dotnet all the things

test/Microsoft.Framework.OptionsModel.Test/OptionsTest.cs
Trying to debug some code, looking for inspiration and noticed a duplicated using.
=> using statement duplicated

src/Microsoft.Framework.OptionsModel/project.json
Adding repository information to the packages that are published.
@davidfowl @troydai
=> Add repository information to packages

test/Microsoft.Framework.OptionsModel.Test/OptionsTest.cs
@kirthik FYI, caused by my change in https://github.com/aspnet/Configuration/pull/251
=> Fix usage of Memory configuration

test/Microsoft.Extensions.OptionsModel.Test/OptionsTest.cs, test/Microsoft.Extensions.OptionsModel.Test/project.json
=> Enable tests on CoreCLR.

.gitattributes, .gitignore, .travis.yml, appveyor.yml, build.cmd, build.sh, test/Microsoft.Extensions.Options.Test/project.json
=> Build with dotnet

src/Microsoft.Extensions.Options.ConfigurationExtensions/project.json, src/Microsoft.Extensions.Options/project.json, test/Microsoft.Extensions.Options.Test/project.json
=> Remove netcore50

NuGetPackageVerifier.json, src/Microsoft.Extensions.Options.ConfigurationExtensions/project.json, src/Microsoft.Extensions.Options/project.json
=> Enabled xml doc generation

src/Microsoft.Extensions.Options/project.json
Resolves aspnet/EntityFramework#4708
=> Don't reference design-time facades on Full .NET

.travis.yml
=> Test webhook

src/Microsoft.Extensions.Options/project.json
Part of https://github.com/aspnet/EntityFramework/pull/5021
=> Cross-compile to netcore50 to support EF on UWP

test/Microsoft.Extensions.Options.Test/project.json
=> Migrate tests/samples/tools to portable

src/Microsoft.Extensions.Options/Infrastructure/ConfigureDefaultOptions.cs, src/Microsoft.Extensions.Options/Infrastructure/ConfigureDefaults.cs, test/Microsoft.Extensions.Options.Test/OptionsTest.cs
Needed for https://github.com/aspnet/MetaPackages/issues/117
@ajcvickers
=> Add infrastructure needed for config defaults

build/common.props, build/dependencies.props, src/Microsoft.Extensions.Options.ConfigurationExtensions/Microsoft.Extensions.Options.ConfigurationExtensions.csproj, src/Microsoft.Extensions.Options/Microsoft.Extensions.Options.csproj, test/Microsoft.Extensions.Options.Test/Microsoft.Extensions.Options.Test.csproj
=> Target .NET Standard 2.0

src/Microsoft.Extensions.Options/OptionsSnapshot.cs, test/Microsoft.Extensions.Options.Test/OptionsSnapshotTest.cs
Fixes https://github.com/aspnet/Options/issues/199
cc @ajcvickers @pakrym @divega
=> Fix scoped snapshot bug

src/Microsoft.Extensions.Options/IOptionsMonitorCache.cs, src/Microsoft.Extensions.Options/OptionsCache.cs, src/Microsoft.Extensions.Options/OptionsMonitor.cs, src/Microsoft.Extensions.Options/OptionsServiceCollectionExtensions.cs, test/Microsoft.Extensions.Options.Test/OptionsSnapshotTest.cs
=> IOptionsCache => IOptionsMonitorCache

src/Microsoft.Extensions.Options.ConfigurationExtensions/ConfigurationChangeTokenSource.cs, src/Microsoft.Extensions.Options/IOptionsMonitor.cs, src/Microsoft.Extensions.Options/IOptionsMonitorCache.cs, src/Microsoft.Extensions.Options/OptionsCache.cs, src/Microsoft.Extensions.Options/OptionsMonitor.cs, src/Microsoft.Extensions.Options/OptionsMonitorExtensions.cs, src/Microsoft.Extensions.Options/breakingchanges.netcore.json, test/Microsoft.Extensions.Options.Test/OptionsMonitorTest.cs
@ajcvickers @pakrym @divega 
Action<TOptions, string> is kinda ugly, maybe we should make it an OptionsCallback class or something?
=> Add name support for Monitor callbacks

src/Microsoft.Extensions.Options/OptionsWrapper.cs
See #215 
I changed this online on github since I don't have the 2.0 SDK on my current computer - so I didn't run a build yet. But Travis/AppVeyor will build the PR anyway, right?!
=> Fixes #215 (Unused methods)

src/Microsoft.Extensions.Options/OptionsCache.cs, src/Microsoft.Extensions.Options/OptionsManager.cs, src/Microsoft.Extensions.Options/OptionsMonitor.cs
Fixes https://github.com/aspnet/Options/issues/220
@ajcvickers @Tratcher
=> Allow null name to mean default instance

src/Microsoft.Extensions.Options/OptionsBuilder.cs, src/Microsoft.Extensions.Options/OptionsFactory.cs, src/Microsoft.Extensions.Options/OptionsValidationException.cs, test/Microsoft.Extensions.Options.Test/OptionsBuilderTest.cs
- Remove extranous overloads that took Name
- Add OptionsType/Name on the validation exception
@ajcvickers I'd like to get this today for 2.2 preview1 ideally
=> Polish for preview1

test/Microsoft.Extensions.Options.Test/OptionsBuilderTest.cs
Print out actual errors so we can see why this test fails in the future, for https://github.com/aspnet/Home/issues/3506
@Eilon @ajcvickers
=> Search for errors instead of expecting strict match
